[package]
name = "lazy-supplements-relay"
edition.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libp2p.workspace = true