[package]
name = "caretta-mobile"
edition.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
test = ["caretta-core/test"]

[dependencies]
caretta-core.workspace = true