[package]
name = "timestamper"
edition.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lazy-supplements.workspace = true