[package]
name = "lazy-supplements-migration"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }
sea-orm-migration.workspace = true
