[package]
name = "lazy-supplements-mobile"
edition.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []
test = ["lazy-supplements-core/test"]

[dependencies]
lazy-supplements-core.workspace = true