[package]
name = "lazy-supplements"
edition.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
automerge = "0.6.1"
libp2p.workspace = true