[package]
name = "caretta-sync-demo-mobile"
edition.workspace = true
version.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
caretta-sync-demo-core.path = "../core"
